In [2]:
from matplotlib import pyplot as plt
import numpy as np
import math as mt
import pandas as pd
from sympy import *

In [3]:
Pw1=40/120
Pw2=40/120
Pw3=40/120

In [4]:
data_frame=pd.read_csv('Iris.csv')
data_frame=data_frame.iloc[:,1:5]
tf1=data_frame.iloc[40:50,:]
tf2=data_frame.iloc[90:100,:]
tf3=data_frame.iloc[140:150,:]
tf=[tf1,tf2,tf3] 
test_frame=pd.concat(tf)
class_frame1=data_frame.iloc[0:40,:]
class_frame2=data_frame.iloc[50:90,:]
class_frame3=data_frame.iloc[100:140,:]

In [5]:
def mean(class_frame):
     mean = class_frame.mean().values
     return np.asarray(mean)

In [6]:
u1=mean(class_frame1)
u2=mean(class_frame2)
u3=mean(class_frame3)
print("u1 = ",u1)
print("u2 = ",u2)
print("u3 = ",u3)

u1 =  [5.0375 3.44   1.4625 0.2325]
u2 =  [6.01   2.78   4.3175 1.35  ]
u3 =  [6.6225 2.96   5.6075 1.99  ]


In [7]:
def get_cov(class_frame):
     return np.asarray(class_frame.cov().values)

In [8]:
Σ1=get_cov(class_frame1)
Σ2=get_cov(class_frame2)
Σ3=get_cov(class_frame3)
print("Σ1 = \n",Σ1)
print("Σ2 = \n",Σ2)
print("Σ3 = \n",Σ3)

Σ1 = 
 [[0.13112179 0.09897436 0.01298077 0.01362179]
 [0.09897436 0.13271795 0.00205128 0.0145641 ]
 [0.01298077 0.00205128 0.02958333 0.00458333]
 [0.01362179 0.0145641  0.00458333 0.00994231]]
Σ2 = 
 [[0.27374359 0.08661538 0.17212821 0.05230769]
 [0.08661538 0.11087179 0.08087179 0.04538462]
 [0.17212821 0.08087179 0.20353205 0.07371795]
 [0.05230769 0.04538462 0.07371795 0.04307692]]
Σ3 = 
 [[0.46794231 0.11041026 0.35777564 0.05125641]
 [0.11041026 0.11323077 0.08107692 0.04625641]
 [0.35777564 0.08107692 0.34532692 0.05930769]
 [0.05125641 0.04625641 0.05930769 0.07425641]]


In [9]:
def class_cond_probab(X,u,Σ):
     Σinv=np.linalg.inv(Σ)
     X_minus_uT=X-u
     X_minus_u=np.transpose(X_minus_uT)
     d1=np.dot(Σinv,X_minus_u)
     d2=np.dot(X_minus_uT,d1)
     return 1/(2*(np.pi**2)*sqrt(abs(np.linalg.det(np.linalg.inv(Σinv)))))*mt.exp((-1/2)*np.dot(X_minus_uT,np.dot(Σinv,X_minus_u)))

In [10]:
def classify(posterior_probab):
     i=posterior_probab.index(max(posterior_probab))
     if i==0:
          return 'Iris-setosa',i
     elif i==1:
          return 'Iris-versicolor',i
     else:
          return 'Iris-virginica',i

In [15]:
error=0
for i in range (30):
     X=np.asarray(test_frame.iloc[i,:])
     p1=class_cond_probab(X,u1,Σ1)*Pw1
     p2=class_cond_probab(X,u2,Σ2)*Pw2
     p3=class_cond_probab(X,u3,Σ3)*Pw3
     p=p1+p2+p3
     posterior_probab=[p1/p,p2/p,p3/p]
     res,j=classify(posterior_probab)
     if i in range(0,9):
          if(j!=0): 
               error+=1
     if i in range(10,19):
          if(j!=1): 
               error+=1
     if i in range(20,29):
          if(j!=2): 
               error+=1
     print("Test flower",i+1,"is classified into the class",res)
accuracy=(1-error/30)*100
print("The accuracy of classification is",accuracy,"%")

Test flower 1 is classified into the class Iris-setosa
Test flower 2 is classified into the class Iris-setosa
Test flower 3 is classified into the class Iris-setosa
Test flower 4 is classified into the class Iris-setosa
Test flower 5 is classified into the class Iris-setosa
Test flower 6 is classified into the class Iris-setosa
Test flower 7 is classified into the class Iris-setosa
Test flower 8 is classified into the class Iris-setosa
Test flower 9 is classified into the class Iris-setosa
Test flower 10 is classified into the class Iris-setosa
Test flower 11 is classified into the class Iris-versicolor
Test flower 12 is classified into the class Iris-versicolor
Test flower 13 is classified into the class Iris-versicolor
Test flower 14 is classified into the class Iris-versicolor
Test flower 15 is classified into the class Iris-versicolor
Test flower 16 is classified into the class Iris-versicolor
Test flower 17 is classified into the class Iris-versicolor
Test flower 18 is classified 

In [12]:
def get_g(X,u,Σ):
    Σinv=np.linalg.inv(Σ)
    X_minus_uT=X-u
    X_minus_u=np.transpose(X_minus_uT)
    return (-1/2)*np.dot(X_minus_uT,np.dot(Σinv,X_minus_u))+(-1/2)*log(np.linalg.det(Σ))    #Pw1=Pw2=Pw3

In [13]:
w=Symbol('w')
x=Symbol('x')
y=Symbol('y')
z=Symbol('z')
X=[w,x,y,z]

In [14]:
gx1=get_g(X,u1,Σ1)
print("Discriminant Function 1: g1(w,x,y,z) =",gx1,'\n')
gx2=get_g(X,u2,Σ2)
print("Discriminant Function 2: g2(w,x,y,z) =",gx2,'\n')
gx3=get_g(X,u3,Σ3)
print("Discriminant Function 3: g3(w,x,y,z) =",gx3,'\n')

Discriminant Function 1: g1(w,x,y,z) = -0.5*(w - 5.0375)*(18.9662099704334*w - 13.7468041472616*x - 6.95996885837586*y - 2.63963857566334*z - 37.4606060352618) - 0.5*(x - 3.44)*(-13.7468041472616*w + 19.00598613724*x + 6.57939373351929*y - 12.0399150292358*z - 2.95414951124992) - 0.5*(y - 1.4625)*(-6.95996885837586*w + 6.57939373351929*x + 39.2173342232132*y - 18.1810720232783*z - 40.7005233752751) - 0.5*(z - 0.2325)*(-2.63963857566334*w - 12.0399150292358*x - 18.1810720232783*y + 130.214948688815*z + 51.02932928937) + 6.6750828692332 

Discriminant Function 2: g2(w,x,y,z) = -0.5*(w - 6.01)*(9.13333334201785*w - 4.07640784883589*x - 9.58250751578472*y + 9.60294701345487*z - 15.150421834527) - 0.5*(x - 2.78)*(-4.07640784883589*w + 17.7117960842808*x + 3.6186862854763*y - 19.9034107906525*z - 13.4936554129601) - 0.5*(y - 4.3175)*(-9.58250751578472*w + 3.6186862854763*x + 23.0046312370379*y - 31.5446870235573*z - 9.20624558786681) - 0.5*(z - 1.35)*(9.60294701345487*w - 19.9034107906525*x 